# =============================================================
# docker-compose.ms-recursos.yml
# Microservicio: Gestión de Recursos y Colaboración
# Spring Boot 3.2 / JDK 21 LTS / Puerto: 8082
# Requiere: docker-compose.bdd.yml, docker-compose.eureka.yml
#           y docker-compose.infra.yml (MailHog) levantados
# Levantar: docker compose -f docker-compose.ms-recursos.yml up -d
# =============================================================

services:

  ms-recursos:
    build:
      context: ../ms-recursos
      dockerfile: Dockerfile
    container_name: ms-recursos
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8082

      # Base de datos
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-recursos:5432/recursos_db
      SPRING_DATASOURCE_USERNAME: recursos_user
      SPRING_DATASOURCE_PASSWORD: recursos_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"

      # Service Discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      # SMTP via MailHog (gratuito, local)
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_FROM: notificaciones@innovatech.cl

      # Actuator
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus,metrics
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
    depends_on:
      db-recursos:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - innovatech-net

networks:
  innovatech-net:
    external: true
