# =============================================================
# docker-compose.ms-proyectos.yml
# Microservicio: Gestión de Proyectos
# Spring Boot 3.2 / JDK 21 LTS / Puerto: 8081
# Requiere: docker-compose.bdd.yml y docker-compose.eureka.yml levantados
# Levantar: docker compose -f docker-compose.ms-proyectos.yml up -d
# =============================================================

services:

  ms-proyectos:
    build:
      context: ../ms-proyectos
      dockerfile: Dockerfile
    container_name: ms-proyectos
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081

      # Base de datos
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-proyectos:5432/proyectos_db
      SPRING_DATASOURCE_USERNAME: proyectos_user
      SPRING_DATASOURCE_PASSWORD: proyectos_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"

      # Service Discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      # Actuator (expone métricas para Prometheus)
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus,metrics
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
    depends_on:
      db-proyectos:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - innovatech-net

networks:
  innovatech-net:
    external: true
